---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: railsapp
  namespace: railsapp
spec:
  destination:
    namespace: railsapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: "image.tag"
        value: {{ .Values.image.tag }}
    chart: railsapp
    repoURL: https://shabbirsaifee92.github.io/helm-charts/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
