apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsapp
  labels:
spec:
  selector:
    matchLabels:
      app: railsapp
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SECRET_KEY_BASE
            value: secret
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
